version: '3'

services:
#  tasks:
#    environment:
#      ENV : "DEV"
#    build:
#      context:  ../
#      dockerfile: ./build/tasks/Dockerfile
#    networks:
#      - my_network
#  codechecker:
#    environment:
#      ENV: "DEV"
#    build:
#      context: ../
#      dockerfile: ./build/codechecker/Dockerfile
#    networks:
#      - my_network
#  api-gateway:
#    environment:
#      ENV: "DEV"
#    build:
#      context: ../
#      dockerfile: ./build/api-gateway/Dockerfile
#    networks:
#      - my_network
#    ports:
#      - '8085:8080'
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    volumes:
      - pgdata_tasks:/var/lib/postgresql/data
    networks:
      - my_network
    ports:
      - "5436:5432"
  mongodb:
    container_name: mongo_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongodata_codechecker:/data/db
    restart: always
    networks:
      - my_network
    ports:
      - "27018:27017"

  redis:
    image: docker.io/bitnami/redis:7.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6380:6379'
    volumes:
      - redisdata_tasks:/bitnami/cache/data
volumes:
  pgdata_tasks:
    driver: local
  redisdata_tasks:
    driver: local
  mongodata_codechecker:
    driver: local
networks:
  my_network: