docker:
  postgres:
    host: postgres
    port: 5432
    username: postgres
    password: postgres
    name: tasks
  redis:
    host: cache
    port: 6379
localhost:
  postgres:
    host: localhost
    port: 5436
    username: postgres
    password: postgres
    name: tasks
  redis:
    host: localhost
    port: 6380
secret-token: this_secret_token
testcase: 5
